let recipes = [
  {
    armor: [
      { craft: 'Armour of the Eternals', ingredients: [ 'Eternal Artefact', 'Eternal Plate', 'Metal Scraps',' Source Orb' ]},
      { craft: 'Cloth Scraps', ingredients: [ 'Any Cutting Tool', 'Bedlinen' ]},
      { craft: 'Handmade Chain Armour', ingredients: [ 'Metal Scraps', 'Needle and Thread' ]},
      { craft: 'Handmade Cloth Shirt', ingredients: [ 'Cloth Scraps', 'Needle and Thread' ]},
      { craft: 'Handmade Leather Armour', ingredients: [ 'Leather Scraps', 'Needle and Thread' ]},
      { craft: 'Handmade Mage Armour', ingredients: [ 'Cloth Scraps', 'Needle and Thread', 'Pixie Dust' ]},
      { craft: 'Handmade Plate Armour', ingredients: [ 'Anvil', 'Plate Scraps' ]},
      { craft: 'Handmade Plate Armour', ingredients: [ 'Anvil', 'Any Hammer', 'Plate Scraps' ]},
      { craft: 'Handmade Scale Armour', ingredients: [ 'Anvil', 'Any Hammer', 'Scale Scraps' ]},
      { craft: 'Handmade Shield', ingredients: [ 'Metal Scraps', 'Wood Chips' ]},
      { craft: 'Leather Scraps', ingredients: [ 'Animal Hide', 'Any Knife' ]},
      { craft: 'Needle and Thread', ingredients: [ 'Needle', 'Thread' ]},
      { craft: 'Yarn', ingredients: [	'Wool' ]}
    ],
    arrows: [
      { craft: 'Arrow Shaft', ingredients: [ 'Any Cutting Tool', 'Short Stick' ]},
      { craft: 'Arrowhead', ingredients: [ 'Any Cutting Tool', 'Bone' ]},
      { craft: 'Arrowhead', ingredients: [ 'Any Cutting Tool',	'Sharp Rock' ]},
      { craft: 'Blessed Water Arrow', ingredients: [ 'Source Orb', 'Water Arrow' ]},
      { craft: 'Blessed Water Arrow', ingredients: [ 'Arrow Shaft', 'Blessed Water Arrowhead' ]},
      { craft: 'blessed Water Arrowhead', ingredients: [ 'Source Orb', 'Water Arrowhead' ]},
      { craft: 'Charming Arrow', ingredients: [ 'Arrow Shaft', 'Charming Arrowhead' ]},
      { craft: 'Charming Arrowhead', ingredients: [ 'Arrowhead', 'Jar of Honey' ]},
      { craft: 'Explosive Arrow', ingredients: [ 'Arrow Shaft', 'Explosive Arrowhead' ]},
      { craft: 'Explosive Arrowhead', ingredients: [ 'Any Oil Source', 'Fire Arrowhead' ]},
      { craft: 'Fire Arrow', ingredients: [ 'Arrow Shaft', 'Fire Arrowhead' ]},
      { craft: 'Fire Arrowhead', ingredients: [ 'Arrowhead', 'Fire Essence' ]},
      { craft: 'Freezing Arrow', ingredients: [ 'Arrow Shaft', 'Freezing Arrowhead' ]},
      { craft: 'Freezing Arrowhead', ingredients: [ 'Arrowhead', 'Water Essence' ]},
      { craft: 'Knockdown Arrow', ingredients: [ 'Arrow Shaft', 'Knockdown Arrowhead' ]},
      { craft: 'Knockdown Arrowhead', ingredients: [ 'Antler', 'Any Cutting Tool' ]},
      { craft: 'Knockdown Arrowhead', ingredients: [ 'Adult Antler', 'Any Cutting Tool' ]},
      { craft: 'Necro Fire Arrowhead', ingredients: [ 'Fire Arrowhead', 'Source Orb' ]},
      { craft: 'Poison Arrow', ingredients: [ 'Arrow Shaft', 'Poisoned Arrowhead' ]},
      { craft: 'Poisoncloud Arrow', ingredients: [ 'Arrow Shaft', 'Poisoncloud Arrowhead' ]},
      { craft: 'Poisoncloud Arrowhead', ingredients: [ 'Arrowhead', 'Earth Essence' ]},
      { craft: 'Poisoned Arrowhead', ingredients: [ 'Any Poison Source', 'Arrowhead' ]},
      { craft: 'Shocking Arrow', ingredients: [ 'Arrow Shaft', 'Shocking Arrowhead' ]},
      { craft: 'Shocking Arrowhead', ingredients: [ 'Air Essence', 'Arrowhead' ]},
      { craft: 'Shocking Arrowhead', ingredients: [ 'Any Cutting Tool', 'Any Tooth' ]},
      { craft: 'Short Stick', ingredients: [ 'Any Cutting Tool', 'Long Branch' ]},
      { craft: 'Slowdown Arrow', ingredients: [ 'Arrow Shaft', 'Slowdown Arrowhead' ]},
      { craft: 'Slowdown Arrowhead', ingredients: [ 'Any Oil Source', 'Arrowhead' ]},
      { craft: 'Smokescreen Arrow', ingredients: [ 'Arrow Shaft', 'Smokescreen Arrowhead' ]},
      { craft: 'Static Cloud Arrow', ingredients: [ 'Arrow Shaft', 'Static Cloud Arrowhead' ]},
      { craft: 'Static Cloud Arrowhead', ingredients: [ 'Air Essence', 'Arrowhead' ]},
      { craft: 'Steamcloud Arrow', ingredients: [ 'Arrow Shaft 	Steamcloud Arrowhead' ]},
      { craft: 'Steamcloud Arrowhead', ingredients: [ 'Any Water Source', 'Fire Arrowhead' ]},
      { craft: 'Water Arrow', ingredients: [ 'Arrow Shaft', 'Water Arrowhead' ]},
      { craft: 'Water Arrowhead', ingredients: [ 'Any Water Source', 'Arrowhead' ]},
    ],
    food: [
      { craft: 'Apple Juice', ingredients: [ 'Apple', 'Empty Cup' ]},
      { craft: 'Apple Pie', ingredients: [ 'Apple Pie Dough', 'Oven' ]},
      { craft: 'Apple Pie Dough', ingredients: [ '	Apple', 'Dough' ]},
      { craft: 'Boiled Potato', ingredients: [ 'Cooking Pot', 'Potato' ]},
      { craft: 'Bottle of Beer', ingredients: [ 'Beer barrel', 'Empty Bottle' ]},
      { craft: 'Bottle of Water', ingredients: [ 'Any Water Source', 'Empty Bottle' ]},
      { craft: 'Bottle of Wine', ingredients: [ 'Empty Bottle', 'Wine barrel' ]},
      { craft: 'Bread', ingredients: [ 'Dough', 'Oven' ]},
      { craft: 'Cheese', ingredients: [ 'Cheese Bread Dough', 'Oven' ]},
      { craft: 'Cheese', ingredients: [ 'Cheese', 'Dough' ]},
      { craft: 'Cold Fries', ingredients: [ 'Any Cutting Tool', 'Potato' ]},
      { craft: 'Cold Mashed Potatoes', ingredients: [ 'Any Hammer', 'Potato' ]},
      { craft: 'Cup of Beer', ingredients: [ 'Beer barrel', 'Empty Cup' ]},
      { craft: 'Cup of Lemonade', ingredients: [ 'Empty Cup', 'Lemon' ]},
      { craft: 'Cup of Tea', ingredients: [ 'Cup of Water', 'Tea Herbs' ]},
      { craft: 'Cup of Water', ingredients: [ 'Any Water Source', 'Empty Cup' ]},
      { craft: 'Cyseal Fish Pie', ingredients: [ 'Fish Pie Dough', 'Oven' ]},
      { craft: 'Dinner', ingredients: [ 'Any Raw food', 'Cooking Station' ]},
      { craft: 'Dinner', ingredients: [ 'Any Raw food', 'Oven' ]},
      { craft: 'Dough', ingredients: [ 'Any Water Source', 'Flour' ]},
      { craft: 'Dough', ingredients: [ 'Flour', 'Milk' ]},
      { craft: 'Dough', ingredients: [ 'Eggs', 'Flour', 'Milk' ]},
      { craft: 'Dwarven Stew', ingredients: [ 'Bottle of Beer', 'Dinner' ]},
      { craft: 'Elven Stew', ingredients: [ 'Dinner', 'Tomato Sauce' ]},
      { craft: 'Fish Pie Dough', ingredients: [ 'Any Fish', 'Dough' ]},
      { craft: 'Flour', ingredients: [ 'Mortar And Pestle', 'Wheat' ]},
      { craft: 'Glass of Wine', ingredients: [ 'Empty Cup', 'Grapes' ]},
      { craft: 'Glass of Wine', ingredients: [ 'Empty Cup', 'Wine barrel' ]},
      { craft: 'Jar of Honey', ingredients: [ 'Beehive', 'Empty Honey Jar' ]},
      { craft: 'Mashed Potatoes', ingredients: [ 'Boiled Potato', 'Milk' ]},
      { craft: 'Mashed Potatoes', ingredients: [ 'Cold Mashed Potatoes', 'Cooking Station' ]},
      { craft: 'Milk', ingredients: [ 'Empty Cup', 'Milk Jug' ]},
      { craft: 'Milk and Honey', ingredients: [ 'Jar of Honey', 'Milk' ]},
      { craft: 'Mug of Beer', ingredients: [ 'Beer barrel', 'Empty Mug' ]},
      { craft: 'Mug of Lemonade', ingredients: [ 'Empty Mug', 'Lemon' ]},
      { craft: 'Mug of Water', ingredients: [ 'Any Water Source', 'Empty Mug' ]},
      { craft: 'Orange Juice', ingredients: [ 'Empty Cup', 'Orange' ]},
      { craft: 'Pizza', ingredients: [ 'Oven', 'Pizza Dough' ]},
      { craft: 'Pizza Dough', ingredients: [ 'Dough', 'Tomato Sauce' ]},
      { craft: 'Porridge', ingredients: [ 'Milk', 'Wheat' ]},
      { craft: 'Potato Porridge', ingredients: [ 'Milk', 'Potato' ]},
      { craft: 'Pumpkin Soup', ingredients: [ 'Cooking Station', 'Pumpkin' ]},
      { craft: 'Rivellon Fries', ingredients: [ 'Cold Fries', 'Cooking Station' ]},
      { craft: 'Tomato Sauce', ingredients: [ 'Any Hammer', 'Tomato' ]}
    ],
    grenades: [
      { craft: 'Bottle Filled With Oil', ingredients: [ 'Any Oil Source', 'Empty Bottle' ]},
      { craft: 'Cluster Grenade', ingredients: [ 'Empty Grenade', 'Fire Essence' ]},
      { craft: 'Cursed Poison Flask', ingredients: [ 'Any Poison Bottle', 'Source Orb' ]},
      { craft: 'Firestorm Grenade', ingredients: [ 'Bottle Filled With Oil', 'Fuse' ]},
      { craft: 'Fuse', ingredients: [ 'Rope' ]},
      { craft: 'Holy Hand Grenade', ingredients: [ 'Sovereign\'s Orb', 'Starfish' ]},
      { craft: 'Love Grenade', ingredients: [ 'Empty Perfume Bottle', 'Jar of Honey' ]},
      { craft: 'Mind Maggot Grenade', ingredients: [ 'A Jar of Mind Maggots', 'Empty Grenade' ]},
      { craft: 'Oil Flask', ingredients: [ 'Any Oil Source', 'Empty Flask' ]},
      { craft: 'Razzle Dazzle Grenade', ingredients: [ 'Any Air Resistance Potion', 'Empty Canister' ]},
      { craft: 'Razzle Dazzle Grenade', ingredients: [ 'Empty Canister', 'Jellyroom' ]},
      { craft: 'Terror Grenade', ingredients: [ 'Empty Canister', 'Tormented Soul' ]},
      { craft: 'Thunderbolt Grenade', ingredients: [ 'Air Essence', 'Empty Canister' ]},
      { craft: 'Tremor Grenade', ingredients: [ 'Earth Essence', 'Empty Canister' ]},
      { craft: 'Water Balloon', ingredients: [ 'Any Water Source', 'Intestines' ]},
    ],
    potions: [
      { craft: 'Any Poison Bottle', ingredients: [ 'Any Healing Potion 	Zaikk\'s Talon' ]},
      { craft: 'Arrowhead', ingredients: [ '	Any Cutting Tool 	Sharp Piece of Metal' ]},
      { craft: 'Ferocity Herbmix', ingredients: [ 'Augmentor 	Drudana' ]},
      { craft: 'Giant Healing Potion', ingredients: [ 'Huge Healing Potion' ]},
      { craft: 'Giant Poison Potion', ingredients: [ 'Huge Poison Bottle' ]},
      { craft: 'Healing Elixir', ingredients: [ 'Empty Potion Bottle 	Yarrow Flower' ]},
      { craft: 'Healing Potion', ingredients: [ 'Medium Healing Potion' ]},
      { craft: 'Huge Earth Resistance Potion', ingredients: [ 'Large Earth Resistance Potion' ]},
      { craft: 'Huge Healing Potion', ingredients: [ 'Healing Potion' ]},
      { craft: 'Huge Poison Bottle', ingredients: [ 'Large Poison Bottle' ]},
      { craft: 'Large Earth Resistance Potion', ingredients: [ 'Medium Earth Resistance Potion' ]},
      { craft: 'Large Magic Armor Potion', ingredients: [ 'Medium Magic Armor Potion' ]},
      { craft: 'Large Physical Armour Potion', ingredients: [ 'Medium Physical Armour Potion' ]},
      { craft: 'Large Poison Bottle', ingredients: [ 'Medium Poison Bottle' ]},
      { craft: 'Medium Earth Resistance Potion', ingredients: [ 'Earth Resistance Potion' ]},
      { craft: 'Medium Healing Potion', ingredients: [ 'Minor Healing Potion' ]},
      { craft: 'Medium Magic Armor Potion', ingredients: [ 'Small Magic Armor Potion' ]},
      { craft: 'Medium Physical Armour Potion', ingredients: [ 'Physical Armor Potion' ]},
      { craft: 'Medium Poison Bottle', ingredients: [ 'Small Poison Bottle' ]},
      { craft: 'Minor Constitution Potion', ingredients: [ 'Empty Potion Bottle 	Farhangit' ]},
      { craft: 'Minor Finesse Potion', ingredients: [ 'Boletus 	Empty Potion Bottle' ]},
      { craft: 'Minor Healing Potion', ingredients: [ 'Empty Potion Bottle 	Penny Bun Mushroom' ]},
      { craft: 'Minor Resist All Potion', ingredients: [ 'Empty Potion Bottle 	Trumpet of Death' ]},
      { craft: 'Minor Strength Potion', ingredients: [ 'Amethyst Deceiver 	Empty Potion Bottle' ]},
      { craft: 'Minor Wits Potion', ingredients: [ 'Empty Potion Bottle 	Puffball' ]},
      { craft: 'Physical Armor Potion', ingredients: [ 'Amadouvier 	Empty Potion Bottle' ]},
      { craft: 'Small Air Resistance Potion', ingredients: [ 'Empty Potion Bottle 	Jellyroom' ]},
      { craft: 'Small Earth Resistance Potion', ingredients: [ 'Earth Tongue Mushroom 	Empty Potion Bottle' ]},
      { craft: 'Small Fire Resistance Potion', ingredients: [ 'Empty Potion Bottle 	Guepinia Mushroom' ]},
      { craft: 'Small Magic Armor Potion', ingredients: [ 'Empty Potion Bottle 	Whisperwood' ]},
      { craft: 'Small Poison Bottle', ingredients: [ 'Empty Potion Bottle 	Ooze Barrel' ]},
      { craft: 'Small Poison Bottle', ingredients: [ 'Minor Healing Potion 	Zaikk\'s Talon' ]},
      { craft: 'Small Poison Bottle', ingredients: [ 'Empty Potion Bottle 	Fly Agaric Mushroom' ]},
      { craft: 'Small Water Resistance Potion', ingredients: [ 'Bluegill Mushroom 	Empty Potion Bottle' ]},
      { craft: 'Stoneskin Potion', ingredients: [ 'Earth Essence 	Empty Potion Bottle' ]},
    ],
    runes: [
      { craft: 'Any Giant Rune', ingredients: [ 'Any Large Rune', 'Superior Pixie Dust' ]},
      { craft: 'Any Large Rune', ingredients: [ 'Any Medium Rune', 'Pixie Dust' ]},
      { craft: 'Any Medium Rune', ingredients: [ 'Any Small Rune', 'Pixie Dust' ]},
      { craft: 'Any Mystical Rune', ingredients: [ 'Any Giant Rune', 'Mystical Rune Frame' ]},
      { craft: 'Any Rune of Power', ingredients: [ 'Any Giant Rune', 'Rune Frame of Power' ]},
      { craft: 'Small Flame Rune', ingredients: [ 'Any Oil Source', 'Pixie Dust 	Wood Chips' ]},
      { craft: 'Small Frost Rune', ingredients: [ 'Any Water Source', 'Metal Scraps 	Pixie Dust' ]},
      { craft: 'Small Masterwork Rune', ingredients: [ 'Any Wine Source', 'Livewood Log 	Pixie Dust' ]},
      { craft: 'Small Rock Rune', ingredients: [ 'Any Beer Source', 'Any Rock', 'Pixie Dust' ]},
      { craft: 'Small Thunder Rune', ingredients: [ 'Any Gold', 'Any Water Source', 'Pixie Dust' ]},
      { craft: 'Small Venom Rune', ingredients: [ 'Any Bone', 'Any Poison Source', 'Pixie Dust' ]},
    ],
    scrolls: [
      { craft: 'Acid Spores Scroll', ingredients: [	'Livewood Log', 'Sheet of Paper', 'Source Orb' ]},
      { craft: 'Apotheosis Scroll', ingredients: [	'Bead', 'Sheet of Paper', 'Source Orb' ]},
      { craft: 'Apportation Scroll', ingredients: [	'High Quality Air Essence', 'Rope', 'Sheet of Paper' ]},
      { craft: 'Armour of Frost Scroll', ingredients: ['Bluegill Mushroom', 'Sheet of Paper', 'Water Essence' ]},
      { craft: 'Artillery Plant Scroll', ingredients: [	'Earth Tongue Mushroom', 'Sheet of Paper', 'Source Orb' ]},
      { craft: 'Black Shroud Scroll', ingredients: [ 'Creepy Eye', 'Sheet of Paper', 'Source Orb' ]},
      { craft: 'Blinding Radiance Scroll', ingredients: [	'Air Essence', 'Any Gold', 'Sheet of Paper' ]},
      { craft: 'Blood Sucker Scroll', ingredients: [	'Penny Bun Mushroom', 'Shadow Essence', 'Sheet of Paper' ]},
      { craft: 'Bone Cage Scroll', ingredients: [	'Fish Bone', 'High Quality Shadow Essence', 'Sheet of Paper' ]},
      { craft: 'Bonedust', ingredients: [	'Bone', 'Mortar And Pestle ' ]},
      { craft: 'Bull Horns Scroll', ingredients: [	'Antler', 'Life Essence', 'Sheet of Paper' ]},
      { craft: 'Chain Lightning Scroll', ingredients: [	'Sheet of Paper', 'Source Orb', 'Wool' ]},
      { craft: 'Chain Lightning Scroll', ingredients: [	'Sheet of Paper', 'Source Orb', 'Yarn' ]},
      { craft: 'Chameleon Skin Scroll', ingredients: [	'Life Essence', 'Long Rat Tail', 'Sheet of Paper' ]},
      { craft: 'Charm Scroll', ingredients: [	'Alien Tormented Soul', 'Jar of Honey 	Sheet of Paper' ]},
      { craft: 'Chicken Claw Scroll', ingredients: [	'Chicken Foot', 'Life Essence 	Sheet of Paper' ]},
      { craft: 'Contamination Scroll', ingredients: [	'Earth Essence', 'Intestines 	Sheet of Paper' ]},
      { craft: 'Curse Scroll', ingredients: [	'Any Voidwoken Fish/Food', 'High Quality Shadow Essence 	Sheet of Paper' ]},
      { craft: 'Decaying Touch Scroll', ingredients: [	'Eye', 'Shadow Essence', 'Sheet of Paper' ]},
      { craft: 'Dimensional Bolt Scroll', ingredients: [	'Pepper', 'Sheet of Paper', 'Tormented Soul' ]},
      { craft: 'Earthquake Scroll', ingredients: [	'Clay', 'High Quality Earth Essence', 'Sheet of Paper' ]},
      { craft: 'Electric Discharge Scroll', ingredients: [	'Air Essence', 'Rabbit\'s Paw', 'Sheet of Paper' ]},
      { craft: 'Elemental Totem Scroll', ingredients: [	'Sheet of Paper', 'Tormented Soul', 'Wooden Figurine' ]},
      { craft: 'Epidemic of Fire Scroll', ingredients: [	'Large Tusk', 'Sheet of Paper', 'Source Orb' ]},
      { craft: 'Equalize Scroll', ingredients: [	'Alien Life Essence', 'Pilgrim\'s Shell', 'Sheet of Paper' ]},
      { craft: 'Ethereal Storm Scroll', ingredients: [	'Carrot', 'Sheet of Paper', 'Source Orb' ]},
      { craft: 'Farsight Infusion Scroll', ingredients: [	'Jar of Honey', 'Sheet of Paper', 'Tormented Soul' ]},
      { craft: 'Favourable Wind Scroll', ingredients: [	'Air Essence', 'Panties', 'Sheet of Paper' ]},
      { craft: 'Feather', ingredients: [	'Any Cutting Tool', 'Pillow ' ]},
      { craft: 'Fire Brand Scroll', ingredients: [	'Alien Fire Essence', 'Fang', 'Sheet of Paper' ]},
      { craft: 'Fire Whip Scroll', ingredients: [	'High Quality Fire Essence', 'Sheet of Paper 	Voidwoken Spike' ]},
      { craft: 'Fireball Scroll', ingredients: [	'Fire Essence', 'Sharp Claw', 'Sheet of Paper' ]},
      { craft: 'Flaming Crescendo Scroll', ingredients: [	'Alien Fire Essence', 'Needle', 'Sheet of Paper' ]},
      { craft: 'Flaming Tongues Scroll', ingredients: [	'Adult Antler', 'High Quality Air Essence', 'Sheet of Paper' ]},
      { craft: 'Fortify Scroll', ingredients: ['Sheet of Paper', 'Whisperwood' ]},
      { craft: 'Fossil Strike Scroll', ingredients: [	'Any Rock', 'Earth Essence', 'Sheet of Paper' ]},
      { craft: 'Grasp of the Starved Scroll', ingredients: [	'Disembodied Hand', 'High Quality Shadow Essence 	Sheet of Paper' ]},
      { craft: 'Grasp of the Starved Scroll', ingredients: [	'Disembodied Hand', 'Sheet of Paper', 'Source Orb' ]},
      { craft: 'Hail Strike Scroll', ingredients: [	'Chub Fish', 'High Quality Water Essence', 'Sheet of Paper' ]},
      { craft: 'Haste Scroll', ingredients: [	'Claw', 'Fire Essence', 'Sheet of Paper' ]},
      { craft: 'Haste Scroll', ingredients: [	'Antler', 'Fire Essence', 'Sheet of Paper' ]},
      { craft: 'Healing Ritual Scroll', ingredients: [	'Sheet of Paper', 'Starfish', 'Water Essence' ]},
      { craft: 'Heart of Steel Scroll', ingredients: [	'Any Metal', 'Life Essence', 'Sheet of Paper' ]},
      { craft: 'Ignition Scroll', ingredients: [	'Fire Essence', 'Sheet of Paper', 'Tusk' ]},
      { craft: 'Impalement Scroll', ingredients: [	'Earth Essence', 'Sharp Piece of Metal', 'Sheet of Paper' ]},
      { craft: 'Infect Scroll', ingredients: [	'Intestines', 'Shadow Essence', 'Sheet of Paper' ]},
      { craft: 'Laser Ray Scroll', ingredients: [	'High Quality Fire Essence 	Nine Inch Nails 	Sheet of Paper' ]},
      { craft: 'Lightning Bolt Scroll', ingredients: [	'Air Essence', 'Rabbit\'s Paw', 'Sheet of Paper' ]},
      { craft: 'Living on the Edge', ingredients: [	'High Quality Shadow Essence', 'Raw Lumpy Giblets', 'Sheet of Paper' ]},
      { craft: 'Living Wall Scroll', ingredients: [	'Alien Earth Essence', 'Augmentor', 'Sheet of Paper' ]},
      { craft: 'Medusa Head Scroll', ingredients: [	'Animal Scales', 'Sheet of Paper', 'Source Orb' ]},
      { craft: 'Mend Metal Scroll', ingredients: [	'Earth Essence', 'Sheet of Paper', 'Stardust' ]},
      { craft: 'Moondust', ingredients: [	'Moonstone', 'Mortar And Pestle ' ]},
      { craft: 'Mush of Wood', ingredients: [	'Any Water Source', 'Wood Chips ' ]},
      { craft: 'Mush of Wood', ingredients: [	'Beehive', 'Wood Chips ' ]},
      { craft: 'Nether Swap Scroll', ingredients: [	'Air Essence', 'Chanterelle', 'Sheet of Paper' ]},
      { craft: 'Peace of Mind Scroll', ingredients: [	'Crab\'s Claw', 'Fire Essence', 'Sheet of Paper' ]},
      { craft: 'Pixie Dust', ingredients: [	'Bonedust', 'Stardust ' ]},
      { craft: 'Pixie Dust', ingredients: [	'Moondust', 'Stardust ' ]},
      { craft: 'Planar Gateway Scroll', ingredients: [	'Grapes', 'Sheet of Paper', 'Source Orb' ]},
      { craft: 'Poison Dart Scroll', ingredients: [	'Earth Essence', 'Fly Agaric Mushroom', 'Sheet of Paper' ]},
      { craft: 'Poison Wave Scroll', ingredients: [	'High Quality Earth Essence', 'Sheet of Paper', 'Slime' ]},
      { craft: 'Pressure Spike Scroll', ingredients: [	'Handkerchief', 'High Quality Air Essence ', 'Sheet of Paper' ]},
      { craft: 'Pyroclastic Eruption Scroll', ingredients: [	'Eternal Tablet', 'Sheet of Paper', 'Source Orb' ]},
      { craft: 'Rain Scroll', ingredients: [	'Herring 	Sheet of Paper', 'Water Essence' ]},
      { craft: 'Raise Bloated Corpse Scroll', ingredients: [	'Raw Red Meat', 'Shadow Essence', 'Sheet of Paper' ]},
      { craft: 'Raise Bonepile Scroll', ingredients: [	'Ancient Human Skull', 'High Quality Shadow Essence', 'Sheet of Paper' ]},
      { craft: 'Rallying Cry Scroll', ingredients: [	'Garlic', 'Sheet of Paper', 'Tormented Soul' ]},
      { craft: 'Reactive Armor Scroll', ingredients: [	'High Quality Earth Essence', 'Sheet of Paper', 'Trumpet of Death' ]},
      { craft: 'Restoration Scroll', ingredients: [	'Penny Bun Mushroom', 'Sheet of Paper', 'Water Essence' ]},
      { craft: 'Resurrection Scroll', ingredients: [	'Life Essence', 'Sheet of Paper', 'Water Essence' ]},
      { craft: 'Searing Daggers Scroll', ingredients: [	'Any Tooth', 'Fire Essence', 'Sheet of Paper' ]},
      { craft: 'Shackles of Pain Scroll', ingredients: [	'High Quality Shadow Essence', 'Sheet of Paper', 'Skull' ]},
      { craft: 'Shatter Scroll', ingredients: [	'Alien Water Essence', 'Mackerel', 'Sheet of Paper' ]},
      { craft: 'Sheet of Paper', ingredients: [	'Mush of Wood', 'Oven ' ]},
      { craft: 'Shocking Touch Scroll', ingredients: [	'Air Essence', 'Flour', 'Sheet of Paper' ]},
      { craft: 'Shocking Touch Scroll', ingredients: [	'Air Essence', 'Nine Inch Nails', 'Sheet of Paper' ]},
      { craft: 'Silencing Stare Scroll', ingredients: [	'Alien Shadow Essence', 'Goo', 'Sheet of Paper' ]},
      { craft: 'Skin Graft Scroll', ingredients: [	'Animal Scales', 'Life Essence', 'Sheet of Paper' ]},
      { craft: 'Soothing Cold Scroll', ingredients: [	'Red Snapper', 'Sheet of Paper', 'Water Essence' ]},
      { craft: 'Soul Mate Scroll', ingredients: [	'High Quality Tormented Soul', 'Sheet of Paper', 'Wheat' ]},
      { craft: 'Spider Legs Scroll', ingredients: [	'Anthropod Leg 	Life Essence 	Sheet of Paper' ]},
      { craft: 'Spread Your Wings Scroll', ingredients: [	'Life Essence', 'Sheet of Paper', 'Sinew' ]},
      { craft: 'Stardust', ingredients: [	'Mortar And Pestle', 'Stardust Herb ' ]},
      { craft: 'Steam Lance Scroll', ingredients: [	'Sheet of Paper', 'Source Orb', 'Water Essence' ]},
      { craft: 'Summon Oily Blob Scroll', ingredients: [	'Any Oil Source', 'Life Essence', 'Sheet of Paper' ]},
      { craft: 'Superconductor Scroll', ingredients: [	'Alien Air Essence', 'Jellyroom', 'Sheet of Paper' ]},
      { craft: 'Superior Stardust', ingredients: [	'Mortar And Pestle', 'Superior Stardust Herb ' ]},
      { craft: 'Supernova Scroll', ingredients: [	'High Quality Fire Essence', 'Sharp Tooth', 'Sheet of Paper' ]},
      { craft: 'Teleportation Scroll', ingredients: [	'Air Essence', 'Feather', 'Sheet of Paper' ]},
      { craft: 'Tentacle Lash Scroll', ingredients: [	'Life Essence', 'Rat\'s Tail', 'Sheet of Paper' ]},
      { craft: 'Thread', ingredients: [ 'Hair' ]},
      { craft: 'Tornado Scroll', ingredients: [	'Hair', 'High Quality Air Essence', 'Sheet of Paper' ]},
      { craft: 'Winter Blast Scroll', ingredients: [ 'Plaice', 'Sheet of Paper', 'Water Essence' ]},
    ],
    skillBooks: [
      { craft: 'Apportation Skillbook', ingredients: [ 'Apportation Scroll', 'Blank Skillbook Air' ]},
      { craft: 'Breathing Bubble Skillbook', ingredients: [ 'Any Air Skillbook', 'Any Warrior Skillbook' ]},
    ],
    tools: [
      { craft: 'Big Tongs Roped Together', ingredients: [ 'Leather Scraps', 'Tongs' ]},
      { craft: 'Big Tongs Roped Together', ingredients: [ 'Cloth Scraps', 'Tongs' ]},
      { craft: 'Bowstring', ingredients: [ 'Sinew' ]},
      { craft: 'Improvised Shovel', ingredients: [ 'Bowl', 'Long Branch' ]},
      { craft: 'Lockpicks', ingredients: [ 'Any Hammer', 'Nine Inch Nails' ]},
      { craft: 'Lockpicks', ingredients: [ 'Needle' ]},
      { craft: 'Lockpicks', ingredients: [ 'Key', 'Soap' ]},
      { craft: 'Rope', ingredients: [ 'Yarn' ]}
    ],
    weapons: [
      { craft: 'Crossbow', ingredients:	[ 'Bowstring', 'Crossbow without bowstring' ]},
      { craft: 'Improv Wand', ingredients:	[ 'Short Stick', 'Skull' ]},
      { craft: 'Improv Wand', ingredients:	[ 'Ancient Human Skull', 'Short Stick' ]},
      { craft: 'Improvised Staff', ingredients:	[ 'Long Branch', 'Shell' ]},
      { craft: 'Knife On A Stick', ingredients:	[ 'Any Knife', 'Rope', 'Short Stick' ]},
      { craft: 'Knife On A Stick', ingredients:	[ 'Any Dagger', 'Rope', 'Short Stick' ]},
      { craft: 'Makeshift Club', ingredients: [ '	Long Branch', 'Sharp Rock' ]},
      { craft: 'Makeshift Club', ingredients: [ '	Cloth Scraps', 'Long Branch' ]},
      { craft: 'Makeshift Club', ingredients: [ '	Leather Scraps', 'Long Branch' ]},
      { craft: 'Makeshift Wand', ingredients:	[ 'Short Stick', 'Skull' ]},
      { craft: 'Primitive Harpoon', ingredients:	[ 'Arrowhead', 'Long Branch' ]},
      { craft: 'Primitive Harpoon', ingredients:	[ 'Long Branch', 'Sharp Piece of Metal' ]},
      { craft: 'Sharp Stone On A Big Branch', ingredients: [ 'Long Branch', 'Sharp Rock' ]},
      { craft: 'Sharp Stone On A Stick', ingredients: [ 'Sharp Rock', 'Short Stick' ]},
      { craft: 'Shiv', ingredients:	[ 'Handkerchief', 'Sharp Piece of Metal' ]},
      { craft: 'Shiv', ingredients:	[ 'Leather Scraps', 'Sharp Piece of Metal' ]},
      { craft: 'Shiv', ingredients:	[ 'Cloth Scraps', 'Sharp Piece of Metal' ]},
      { craft: 'Shiv', ingredients:	[ 'Anvil', 'Any Hammer', 'Sharp Piece of Metal' ]},
      { craft: 'Toy Crossbow', ingredients:	[ 'Long Branch', 'Short Stick' ]},
      { craft: 'Twig With A String', ingredients:	[ 'Bowstring', 'Short Stick' ]}
    ]
  }
];